# Use official PHP Apache image
FROM php:8.1-apache

# Install PostgreSQL client libraries and required extensions
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql pgsql \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# # Set working directory
# WORKDIR /var/www/html
COPY ./dockerteam3/php/index.php /var/www/html/index.php

ENV DB_HOST postgresql
ENV DB_USER myuser
ENV DB_PASSWORD mypassword
ENV DB_NAME mydb

# Expose port 80
EXPOSE 80

# Start Apache server
CMD ["apache2-foreground"]
